# Generated by Django 5.2.8 on 2025-11-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
